### ISSUE TITLE
Slicing the MAS datacube

### ISSUE THREAD

**Issue by MohamedNedal** [predsci/PsiPy#113]
Hello, I would like to ask about slicing longitudinal cuts from the MAS model output.
I have a set of 5 points in the Cartesian coordinate system (x,y,z):

```
[(0.6560437400941784, -1.5846997287142082, -0.7860287323182779),
 (0.9545781919458538, -1.7061321757365773, -0.7673182913311284),
 (1.1177970657305458, -1.7960146285896472, -0.7382414547171221),
 (1.1100915007215941, -1.6505608521074704, -1.6923766297741043),
 (1.4891858730440695, -2.017099350236158, -1.3959493819848054)]
 ```
Each point has a different timestamp, but all of them occurred on the same day and almost at the same time (only a few seconds of time difference between them).

I want to sample the datacube of the MAS model to extract the plasma and magnetic field quantities at the same coordinates as those points.
To my knowledge, the MAS datacube is defined in the Spherical coordinate system, and it represents a full Carrington rotation so that each longitudinal slice refers to a certain date and time, right?

I think I have to convert my points from the Cartesian system to the Spherical system and to use [this](https://psipy.readthedocs.io/en/stable/auto_examples/sampling/plot_sampling_data.html#sphx-glr-auto-examples-sampling-plot-sampling-data-py) function, but I am not sure how to use it to extract the plasma values from the MAS datacube at those new coordinates. I need some guidance please.
Thank you; your help is much appreciated

**Comment by thepeteriley** [comment]
Hi Mohamed, 

if the points are at essentially the same time point (seconds are negligible for MHD!), then you just need to convert from the cartesian system to a spherical system. If the Cartesian system is aligned with the spherical system, then it's just a matter of using simple spherical trig to go from one to another.  If it's rotated wrt the other system, it's still a spherical conversion. Then var.sample_at_coords(r,t,p) will retrieve the data for variable, var (e.g., br, rho, etc) at that point. 

You  also mentioned the connection between phi and time. This is more of an equivalency, in that, for a steady-state solution, you can relate phi and t through phi = omega t, where omega is the rotation period of the Sun (25.38 days). However, for the problem you're describing, this is a complication rather than a help. On the other hand, if you want to compare directly with spacecraft observations and plot the results, say, as a function of time, then this would be important. 

-Pete.

**Comment by MohamedNedal** [comment]
Hi Pete, excuse me I'm a bit confused

When I downloaded the MAS datacube (coronal solution) for a specific day and time, I found that the data file has only one timestep, but how does it represent a full Carrington rotation if it has one timestep?
If it represents a Carrington rotation, how can I extract a longitudinal cut at a certain time as observed from the Earth using this relation: `phi = omega t`?

Here are the points after transformation to the spherical coordinate system, and the function I used for this transformation:
```
def cartesian_to_spherical(x, y, z):
    ''' 
    Converts cartesian to spherical coords .. physics convention 
    Suitable for the MAS Model.
    phi         ==> azimuth (lon): east-west position, [-pi, pi] rad --> [-180, 180] deg .. [0, 360] deg in MAS 
    theta       ==> elevation (lat): north-south position, [0, pi] rad --> [0, 180] deg .. [-90, 90] deg in MAS 
    radial dist ==> [0, inf] --> [1, 30] Rs in MAS 
    ''' 
    r = np.sqrt(x**2 + y**2 + z**2)
    theta = np.arccos(z/r)
    phi = np.arctan2(y, x)
    
    return (phi, theta, r)

centroids_locations = [(0.6560437400941784, -1.5846997287142082, -0.7860287323182779),
                         (0.9545781919458538, -1.7061321757365773, -0.7673182913311284),
                         (1.1177970657305458, -1.7960146285896472, -0.7382414547171221),
                         (1.1100915007215941, -1.6505608521074704, -1.6923766297741043),
                         (1.4891858730440695, -2.017099350236158, -1.3959493819848054)]

x = [c[0] for c in centroids_locations]
y = [c[1] for c in centroids_locations]
z = [c[2] for c in centroids_locations]

sph_coords = []
for i,j,k in zip(x,y,z):
    sph_coords.append(cartesian_to_spherical(i, j, k))
```

```
sph_coords = [(-1.1782913690357715, 2.0005239409052087, 1.8866657857536722),
 (-1.0606899515764048, 1.9448083719277456, 2.1002104384640994),
 (-1.0140858914899615, 1.906558327712818, 2.240566730032087),
 (-0.9787288621383149, 2.2757608841434362, 2.6116647800760373),
 (-0.9348377439052153, 2.0788165681615567, 2.869675770929691)]
```

![image](https://github.com/predsci/PsiPy/assets/43330567/e3a1fbf9-e323-4028-a8db-092f3adc4e92)
![image](https://github.com/predsci/PsiPy/assets/43330567/6c5f1727-9bf1-4fc5-a068-1f20e8607e86)
![image](https://github.com/predsci/PsiPy/assets/43330567/05f83a07-8f36-4978-b68b-f5696ff8f1cd)
![image](https://github.com/predsci/PsiPy/assets/43330567/8cee2075-38f9-4e95-b97f-0972e5e6af3f)

**Comment by thepeteriley** [comment]
I'll follow up via email...
