### ISSUE TITLE
Relative location of Earth on an equatorial cut of MAS data

### ISSUE THREAD

**Issue by MohamedNedal** [predsci/PsiPy#115]
Hello, I was wondering how can I show the location of Earth and other bodies or instruments on the equatorial cut in [this example](https://psipy.readthedocs.io/en/stable/auto_examples/visualisation/plot_equatorial_slice.html#sphx-glr-auto-examples-visualisation-plot-equatorial-slice-py).
Do I need to rotate the plot to correct the orientation relative to the Earth's location?
![image](https://github.com/predsci/PsiPy/assets/43330567/9396f2b0-7d07-46f5-b49e-05f1440884bf)

**Comment by thepeteriley** [comment]
Hi Mohamed, 

The MAS results are shown in the Carrington frame, so to add the location of Earth at a point or as a function of time, you'd need to get the ephemerous data in Carrington coordinates. 

The best way would be to use a python call, to a library. I use heliopy and there are examples of its use in the PsiPy documents, but has been deprecated. SunPy can probably do what you need. The most basic way would be to create your own dataset from omniweb:

https://omniweb.gsfc.nasa.gov/coho/helios/heli.html

but if you can use the python routines, that'd be better. 

-Pete

**Comment by MohamedNedal** [comment]
Thank you so much Pete
