### ISSUE TITLE
Sampling values from an equatorial cut of MAS data

### ISSUE THREAD

**Issue by MohamedNedal** [predsci/PsiPy#116]
Hello, I am trying to extract the density value from a 2D polar map representing an equatorial cut of MAS data.
I obtained the location of Earth at the same time of the MAS data file and I rotated the map accordingly so that the location of earth is pointing southward, shown as a dashed yellow line, with a Carrington longitude of 69.9 deg.
Is this implementation correct?
Here is my code:
```python
from matplotlib import colors
from astropy.time import Time
import sunpy.coordinates.frames as frames
import sunpy.coordinates.transformations as transformations
from sunpy.coordinates import get_body_heliographic_stonyhurst

# Get the loc of Earth
obstime = Time('2019-04-03T12:00:00.000')
planet_list = ['earth']
planet_coord = [get_body_heliographic_stonyhurst(this_planet, time=obstime) for this_planet in planet_list]

# Create a Heliographic Carrington Coordinate frame
hgc_frame = frames.HeliographicCarrington(observer='earth', obstime=obstime)

# Convert the Heliographic Stonyhurst Coordinate to Heliographic Carrington Coordinate
hgc_coord = transformations.hgs_to_hgc(planet_coord[0], hgcframe=hgc_frame)

# Plot the MAS density 2D map
fig = plt.figure(figsize=[8,8])
ax = fig.add_subplot(111, projection='polar')
rho.plot_equatorial_cut(ax=ax, norm=colors.LogNorm(vmin=1.5e4, vmax=1e11), cmap='rainbow', cbar_kwargs={'fraction':0.023, 'pad':0.05})

# Rotate the MAS map using the location of Earth
ax.set_theta_zero_location(loc='S', offset=-1*hgc_coord.lon.value)

# Draw the plane of sky
ax.plot([np.pi/2 + np.deg2rad(hgc_coord.lon.value), 3*np.pi/2 + np.deg2rad(hgc_coord.lon.value)], [0, 10], c='black', ls='--', lw=2) # LEFT
ax.plot([np.pi/2 + np.deg2rad(hgc_coord.lon.value), 3*np.pi/2 + np.deg2rad(hgc_coord.lon.value)], [10, 0], c='black', ls='--', lw=2) # RIGHT

# Draw a cricle for the Sun
theta_sun = np.linspace(0, 2*np.pi, 100)
r_sun = np.ones(100)*(1*u.solRad).value
ax.fill(theta_sun, r_sun, ls='-', facecolor='white', zorder=3)

# Sun-Earth line of sight
ax.plot([np.deg2rad(hgc_coord.lon.value), np.deg2rad(hgc_coord.lon.value)], [0, (1*u.AU).to(u.solRad).value], ls='--', c='yellow')
ax.text(np.deg2rad(338)+np.deg2rad(hgc_coord.lon.value), 3, f'To Earth\nCR Lon.:\n{hgc_coord.lon:.2f}', fontsize=10, weight='bold', color='yellow', va='bottom', zorder=10)

# Sampling a point
sample1_lon = 69.9*u.deg
sample1_lat = 0*u.deg
sample1_rad_dist = 2*u.solRad
ax.scatter(np.deg2rad(sample1_lon), sample1_rad_dist, marker='o', s=60, c='w', edgecolors='k', zorder=10)
rho_sample1 = rho.sample_at_coords(sample1_lon, sample1_lat, sample1_rad_dist)
print(f'Density at the white point is: {rho_sample1[0]:.2e}')

sample2_lon = 28*u.deg
sample2_lat = 0*u.deg
sample2_rad_dist = 1.2*u.solRad
ax.scatter(np.deg2rad(sample2_lon), sample2_rad_dist, marker='o', s=60, c='r', edgecolors='k', zorder=10)
rho_sample2 = rho.sample_at_coords(sample2_lon, sample2_lat, sample2_rad_dist)
print(f'Density at the red point is: {rho_sample2[0]:.2e}')

sample3_lon = 17*u.deg
sample3_lat = 0*u.deg
sample3_rad_dist = 3.5*u.solRad
ax.scatter(np.deg2rad(sample3_lon), sample3_rad_dist, marker='o', s=60, c='g', edgecolors='w', zorder=10)
rho_sample3 = rho.sample_at_coords(sample3_lon, sample3_lat, sample3_rad_dist)
print(f'Density at the green point is: {rho_sample3[0]:.2e}')

# Figure settings
ax.set_rmax(3.7)
ax.grid(alpha=0.5, c='w')
y_tick_labels = np.array([1.5, 2.0, 2.5, 3.0, 3.5])
ax.set_yticks(ticks=y_tick_labels)
ax.set_rlabel_position(90)
ax.yaxis.set_tick_params(labelcolor='white')
ax.set_yticklabels(y_tick_labels, fontweight='bold')
plt.show()
```
![image](https://github.com/predsci/PsiPy/assets/43330567/1f751134-8366-43dd-abd3-8ff95ec46a17)

**Comment by thepeteriley** [comment]
Hi Mohamed, 

I'm not sure what's going on, but there are a number of things that don't make sense: 

1. The MAS results for the heliospheric runs go from 30 Rs to 1 AU, so I'm not sure what model results you're showing here. Could it be a coronal solution? 
2. The densities should be on the order of ~few cm-3 at 1 AU. These densities are either in code units and/or from a coronal run? 
3. The model data you're showing doesn't look like a cut through a heliospheric simulation in the equatorial plane. As a basic litmus test, you should see spiral compression regions and rarefactions behind them. 

If you can look into these issues, perhaps by just plotting simple examples from the ReadtheDocs page, that might help diagnose some of them. 

Pete

**Comment by MohamedNedal** [comment]
Hi Pete, thank you for your answer
This is a coronal solution. The white circle in the middle represents the Sun.
I am trying to sample the density values from the MAS data at different locations near to the Sun

**Comment by thepeteriley** [comment]
So these are solar radii then, out to about 3.5? Earth will not be in these solutions then. Are you confusing 1 AU with 1 Rs?

**Comment by MohamedNedal** [comment]
Yes, the white labels 1.5 to 3.5 are in solar radii.
The Earth won't appear here indeed. I obtained its location just to rotate the MAS density map so that the Sun-Earth line of sight will point southward. The black dot represents the Earth, and the black dashed line represents the Sun-Earth line of sight.
Here is the coronal solution (zoomed out) with the Earth location, without any offset rotation
![image](https://github.com/predsci/PsiPy/assets/43330567/a05f4119-b208-411c-868a-8716d7b66db8)
![image](https://github.com/predsci/PsiPy/assets/43330567/301f62be-e8cd-4b8d-bd7b-427a55347456)

Here is the coronal solution after doing the rotation offset using the Earth's longitude at that time
![image](https://github.com/predsci/PsiPy/assets/43330567/7a3cdd45-d027-4f98-9c21-0497f390b9b6)
![image](https://github.com/predsci/PsiPy/assets/43330567/a8c16f34-6192-45fa-bd47-f4cae6add793)

**Comment by thepeteriley** [comment]
Hi Mohamed, 

Then I think that what you're doing is OK, but I'm confused that you're using the coronal results. If you want to compare with Earth observations, you'll need to use the heliospheric solutions. In that case, it's much easier to check the observations with the model results since we've done that many times independently and for lots of intervals. 

Pete

**Comment by MohamedNedal** [comment]
Hi Pete, sorry for the late reply
I'd like to compare the coronal model results with remote observations I'm currently working on.
Thank you so much! :)
Mohamed
