### ISSUE TITLE
br_r0 unexpectedly loaded (ValueError: different number of dimensions on data and dims: 3 vs 4)

### ISSUE THREAD

**Issue by peijin94** [predsci/PsiPy#117]
The file structure looks like this from mhd-web:
<img width="232" alt="image" src="https://github.com/predsci/PsiPy/assets/11596456/587cd0b3-88db-4097-a98c-40e2dd16777f">

But the file loader will look for "br*" (https://github.com/predsci/PsiPy/blob/9c2b1f1bca4af5028f0d806ffb8851a30cf371a7/psipy/io/mas.py#L29) in this case, and it will load br_r0 instead of br002

causing dim mismatch problem:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[20], [line 1](vscode-notebook-cell:?execution_count=20&line=1)
----> [1](vscode-notebook-cell:?execution_count=20&line=1) model['br']
.......................................
    for d in dims:

ValueError: different number of dimensions on data and dims: 3 vs 4
```

The solution could be: to rename the br_r0 in the data production to not start with br (e.g. boundary_br.hdf), or change the file loader to find the same pattern for all variables, or do a sanity check on load.

**Comment by thepeteriley** [comment]
Right, it shouldn't be loading the boundary file by default. The naming of the files can't change, but I'll modify the file loader so that it doesn't pick up none output files by default. For now, if you can just move it out of the directory that should fix the problem. Thanks for the heads-up.

**Comment by peijin94** [comment]
rename boundary file works
