### ISSUE TITLE
The _mas_units for density are not correct.

### ISSUE THREAD

**Issue by AthKouloumvakos** [predsci/PsiPy#23]
The units for density are not correct here:

https://github.com/predsci/PsiPy/blob/87f9cdfaffb3bec6a1c05e367a5e7ac597b413d2/psipy/model/mas.py#L26

The u.N.names is ['N', 'Newton', 'newton'] and this is the problem.

The line should be:

` 'rho': [1 / u.cm**3, 1.67e-16 / 1.67e-24],`

 so `rho.units` to be particles/cm**3.

**Comment by AthKouloumvakos** [comment]
Thank you, it works well now. I close this issue

**Comment by dstansby** [comment]
I'm going to leave this open until a fix is merged. For some reason the one I've tried in #31 doesn't seem to be working
