### ISSUE TITLE
Add some PLUTO test data

### ISSUE THREAD

**Issue by dstansby** [predsci/PsiPy#42]
Currenlty PLUTO models aren't tested in the automatic tests. It would be good to add some test data and run the PLUTO tests on github to avoid situations like https://github.com/predsci/PsiPy/issues/38 popping up again.

**Comment by jj-gonzalez-aviles** [comment]
Hi David. Thanks for checking into this issue. I have many PLUTO data, but I do not have access to upload files; how can I proceed then?.

**Comment by mbennun** [comment]
Hi David,
I just cloned the current version from github and tested it with the output
of a PLUTO. I am still getting the same error as last week.
It is possible that I am doing something wrong and I did not really pull
the updated version.
I have PLUTO test data that I can upload if you give me some
instructions on where you would like this data to be.
Thanks,
Michal

**Comment by dstansby** [comment]
I merged the fix into the `main` branch, so it should work now. Could you upload some test data to https://figshare.com/? I think that's the best way to have the data available for testing through the GitHub automatic tests.

**Comment by mbennun** [comment]
I uploaded a dataset but I have not figured out how to make it public

**Comment by mbennun** [comment]
I finally figured out how to publish the PLUTO data with figshare.
When you download it - put it all in one directory
This link should work: https://doi.org/10.6084/m9.figshare.19401089.v1
