### ISSUE TITLE
ValueError: The points in dimension 0 must be strictly ascending

### ISSUE THREAD

**Issue by thepeteriley** [predsci/PsiPy#47]
An error that I think is a limitation of PsiPy requiring longitude to have only increasing values. Here's an error:
```python
Traceback (most recent call last):
  File "comp_mas_obs_in_situ.py", line 60, in <module>
    sampled = model_var.sample_at_coords(psp_coords.lon,
  File "/Users/pete/miniconda3/envs/psi/lib/python3.8/site-packages/astropy/units/decorators.py", line 253, in wrapper
    return_ = wrapped_function(*func_args, **func_kwargs)
  File "/Users/pete/miniconda3/envs/psi/lib/python3.8/site-packages/psipy/model/variable.py", line 421, in sample_at_coords
    values_x = interpolate.interpn(points, values, xi)
  File "/Users/pete/miniconda3/envs/psi/lib/python3.8/site-packages/scipy/interpolate/interpolate.py", line 2677, in interpn
    raise ValueError("The points in dimension %d must be strictly "
ValueError: The points in dimension 0 must be strictly ascending
(psi) bash>
```
When I plot the variables for this case: 

PSP lon:
[88d08m05.49949755s 88d08m05.49949755s 88d08m05.49949755s ...
 87d17m15.11334387s 87d17m15.11334387s 87d17m15.11334387s]
PSP lat:
[3d42m36.7949427s 3d42m36.7949427s 3d42m36.7949427s ... 1d47m18.20444479s
 1d47m18.20444479s 1d47m18.20444479s]
PSP Radius:
[57939404.07928313 57939404.07928313 57939404.07928313 ...
 55264740.00420908 55264740.00420908 55264740.00420908] km

I think the "dimension 0" is longitude. 

If I do this for a different time interval, then I can get the script to run w/o error. In that case, longitude is increasing. 

Could the issue be that the interpolation doesn't appreciate that longitude is a periodic variable?

**Comment by dstansby** [comment]
Could you post the value of `model_var.phi_coords`? I'm struggling to reproduce this locally.

**Comment by dstansby** [comment]
Hi Pete, I think https://github.com/predsci/PsiPy/pull/53 should have solved this. Can you check with the latest version of the `main` branch?

**Comment by thepeteriley** [comment]
Yes, I think this fixed the longitude wrapping issue. It raises a different issue though  - if the interpolation points in R extend beyond the bounds of the simulation, it returns an error. Not sure if this is reasonable? Perhaps it should default to the minimum value of R in the simulation and post a warning that the interpolation extended beyond the bounds of the simulation and the value was set to the minimum or maximum value? 

Traceback (most recent call last):

  File "/var/folders/zh/vljt07xx0g71gtxxgvbms0hw0000gn/T/ipykernel_40855/3418382174.py", line 1, in <module>
    sampled = model_var.sample_at_coords(psp_coords.lon,

  File "/Users/pete/miniconda3/envs/psi/lib/python3.8/site-packages/astropy/units/decorators.py", line 253, in wrapper
    return_ = wrapped_function(*func_args, **func_kwargs)

  File "/Users/pete/miniconda3/envs/psi/lib/python3.8/site-packages/psipy/model/variable.py", line 430, in sample_at_coords
    raise ValueError(f"At least one point is outside bounds {bounds} in {dim} dimension.")

ValueError: At least one point is outside bounds (29.79271125793457, 236.6672821044922) in r dimension.

24-Mar-22 20:45:32: sys:1: ResourceWarning: unclosed socket <zmq.Socket(zmq.PUSH) at 0x7f99a9496640>

**Comment by dstansby** [comment]
Raising an error is consistent with interpolation routines in `numpy` and `scipy`, so I'd be inclined to leave it as is? Perhpas there's somewhere in the docs that we could add an example of using `np.clip` (https://numpy.org/doc/stable/reference/generated/numpy.clip.html) for users to manually make sure their points are within bounds?

**Comment by thepeteriley** [comment]
If that's reasonable behaviour, that sounds fine to leave it as is. The np.clip idea also seems to address the problem.

**Comment by thepeteriley** [comment]
> Hi Pete, I think #53 should have solved this. Can you check with the latest version of the `main` branch?

It appears that this 'bug' is still present. It's not related just to the wrapping in phi between 360 and zero, but also because of PSP's unique trajectory in Carrington space. Because its initially traveling slower, then faster than the Sun's rotation, the Carrington longitude first decreases, then increases, then decreases, so even when well away from 360/0 the routine still throws an error like:

sampled = model_var.sample_at_coords(lon_psp,lat_psp,r_psp)
Traceback (most recent call last):

  File "/var/folders/zh/vljt07xx0g71gtxxgvbms0hw0000gn/T/ipykernel_48058/4290089244.py", line 1, in <module>
    sampled = model_var.sample_at_coords(lon_psp,lat_psp,r_psp)

  File "/Users/pete/miniconda3/envs/psi/lib/python3.8/site-packages/astropy/units/decorators.py", line 253, in wrapper
    return_ = wrapped_function(*func_args, **func_kwargs)

  File "/Users/pete/miniconda3/envs/psi/lib/python3.8/site-packages/psipy/model/variable.py", line 433, in sample_at_coords
    values_x = interpolate.interpn(points, values, xi)

  File "/Users/pete/miniconda3/envs/psi/lib/python3.8/site-packages/scipy/interpolate/interpolate.py", line 2677, in interpn
    raise ValueError("The points in dimension %d must be strictly "

ValueError: The points in dimension 0 must be strictly ascending

**Comment by mbennun** [comment]
Pete - Can you reorder the PSP data so that the Carrington longitude is
always increasing (of course you will have to reorder all the arrays
accordingly)

**Comment by thepeteriley** [comment]
> Pete - Can you reorder the PSP data so that the Carrington longitude is always increasing (of course you will have to reorder all the arrays accordingly)

Yes, this might work as a quick fix for time-independent solutions, but it shouldn't be required - the radial coordinate decreases then increases around perihelion, so it's not a limitation of the interpolation per se.

**Comment by mbennun** [comment]
The code is using scipy.interpolate.interpn which requires the points in
each dimension to be strictly increasing. So this interpolator has this
limitation

**Comment by dstansby** [comment]
This error is related to the model grid, not the (PSP) coordinates that you're trying to interpolate at. Could you upload one of the magnetic field model outputs that you're trying to use here? Hopefully I can take a look and debug with that.

**Comment by thepeteriley** [comment]
Sure, here are the model output files:

https://www.predsci.com/data/runs/cr2243-high/hmi_mast_mas_std_0201/helio/

**Comment by jj-gonzalez-aviles** [comment]
> Yes, I think this fixed the longitude wrapping issue. It raises a different issue though - if the interpolation points in R extend beyond the bounds of the simulation, it returns an error. Not sure if this is reasonable? Perhaps it should default to the minimum value of R in the simulation and post a warning that the interpolation extended beyond the bounds of the simulation and the value was set to the minimum or maximum value?
> 
> Traceback (most recent call last):
> 
> File "/var/folders/zh/vljt07xx0g71gtxxgvbms0hw0000gn/T/ipykernel_40855/3418382174.py", line 1, in sampled = model_var.sample_at_coords(psp_coords.lon,
> 
> File "/Users/pete/miniconda3/envs/psi/lib/python3.8/site-packages/astropy/units/decorators.py", line 253, in wrapper return_ = wrapped_function(*func_args, **func_kwargs)
> 
> File "/Users/pete/miniconda3/envs/psi/lib/python3.8/site-packages/psipy/model/variable.py", line 430, in sample_at_coords raise ValueError(f"At least one point is outside bounds {bounds} in {dim} dimension.")
> 
> ValueError: At least one point is outside bounds (29.79271125793457, 236.6672821044922) in r dimension.
> 
> 24-Mar-22 20:45:32: sys:1: ResourceWarning: unclosed socket <zmq.Socket(zmq.PUSH) at 0x7f99a9496640>

I faced same issue when try to compare PLUTO data with PSP observations: 

['radialDistance', 'heliographicLatitude', 'heliographicLongitude', 'BR', 'BT', 'BN', 'B', 'VR', 'VT', 'VN', 'ProtonSpeed', 'flow_theta', 'flow_lon', 'protonDensity', 'protonTemp']
[0.45211079 0.45211079 0.45211079 ... 0.44657442 0.44657442 0.44657442] km
Traceback (most recent call last):
  File "/Users/josejuan/psipy_examples/plot_in_situ_comparison_PLUTO.py", line 95, in <module>
    vr_sampled = vr_model.sample_at_coords(psp_coords.lon,
  File "/Users/josejuan/opt/miniconda3/lib/python3.9/site-packages/astropy/units/decorators.py", line 304, in wrapper
    return_ = wrapped_function(*func_args, **func_kwargs)
  File "/Users/josejuan/opt/miniconda3/lib/python3.9/site-packages/psipy/model/variable.py", line 430, in sample_at_coords
    raise ValueError(f"At least one point is outside bounds {bounds} in {dim} dimension.")
ValueError: At least one point is outside bounds (0.14646213, 1.09346367) in r dimension.

**Comment by dstansby** [comment]
I believe this last issue is fixed in https://github.com/predsci/PsiPy/pull/62 - PLUTO models now have correctly assigned AU units for their radial coordinate, and you now have to input a Quantity (instead of a plain numpy array) with length units (e.g. AU, R_sun...) to `sample_at_coords`.
