### ISSUE TITLE
error notification in sample_at_coords

### ISSUE THREAD

**Issue by mbennun** [predsci/PsiPy#61]
When using sample_at_coords, PSP for example can be outside the MAS simulation domain, e.g. below 30Rs for CR 2254.  The error message is not very graceful. It would be better to first check for this and ask the user to remove these time points from the arrays that are being sent to sample_at_coords. Or even do the removal within sample_at_coords and just send a warning that some time points have been removed because they are not in the MAS/PLUTO simulation domain

**Comment by dstansby** [comment]
For points outside the domain the interpolated values could just be `NaN` - would that be better?

**Comment by mbennun** [comment]
That is a good idea.  But is there a way to let the User know that some of the spacecraft coordinates are not within the MAS/PLUTO simulation domain?

**Comment by dstansby** [comment]
Yep, we can raise a warning message that the user will see, but carry on with the interpolation anyway.

**Comment by mbennun** [comment]
Seems good to me
