### ISSUE TITLE
Problem with the example of plotting field lines with pyvista

### ISSUE THREAD

**Issue by MohamedNedal** [predsci/PsiPy#76]
Hello, when I tried the example at: [Examples](https://psipy.readthedocs.io/en/latest/auto_examples/index.html) > [Tracing field lines](https://psipy.readthedocs.io/en/latest/auto_examples/tracing/index.html) > [Field lines with pyvista](https://psipy.readthedocs.io/en/latest/auto_examples/tracing/tracing_pyvista.html#sphx-glr-auto-examples-tracing-tracing-pyvista-py) 

I got this warning: 
`plotter = MASPlotter(model)`

```
/home/mnedal/.conda/envs/psp/lib/python3.9/site-packages/pyvista/plotting/plotting.py:116: UserWarning: 
This system does not appear to be running an xserver.
PyVista will likely segfault when rendering.

Try starting a virtual frame buffer with xvfb, or using
  ``pyvista.start_xvfb()``

  warnings.warn(
``` 
When I run this part, the kernel dies, and no plot is shown up 
```
br = model["br"]
for fline in flines:
    # Set color with polarity near the inner boundary
    color = (
        br.sample_at_coords(
            np.mod(fline.lon[1], 2 * np.pi * u.rad),
            fline.lat[1],
            fline.r[1] * u.R_sun,
        )
        > 0
    )
    color = {0: "red", 1: "blue"}[int(color)]
    plotter.add_fline(fline, color=color)

# Add a sphere at the inner boundary of the model
plotter.add_sphere(np.min(br.r_coords))
plotter.show()
```

**Comment by dstansby** [comment]
Are you running this in a jupyter notebook? If so https://docs.pyvista.org/user-guide/jupyter/index.html should help with getting the 3D viewing working.

**Comment by MohamedNedal** [comment]
Yes, I am using jupyter notebook through a Linux terminal. 
I followed the instructions in that link and tried the examples, but it doesn't show anything. I also tried using `%matplotlib notebook` and `%matplotlib inline` and nothing changed. What should I do?

**Comment by mbennun** [comment]
Can you convert the jupyter notebook to a python script and see if you get the plot when you run the script using the command line on the terminal

**Comment by MohamedNedal** [comment]
I converted it to a python script and ran it using the command line on the terminal. It's been a few hours so far and no output is shown up. Is that normal?

**Comment by mbennun** [comment]
No.  You should have seen the plot basically immediately.  Have you verified that the data is being loaded properly?

**Comment by MohamedNedal** [comment]
It works now! I had to set the displaying kernel `jupyter_backend='panel'` in my notebook. 
Thank you! 
![image](https://user-images.githubusercontent.com/43330567/195702810-4bab93ed-f31c-4efd-b16d-404813974df1.png)
