### ISSUE TITLE
Incorrect tracing for the coronal field lines

### ISSUE THREAD

**Issue by MohamedNedal** [predsci/PsiPy#88]
I would like to trace the field lines for the coronal solution. There is something wrong, I am not exactly sure what it is. 
I expected that the field lines to start from the Sun in the attached plot. 
Here is the code and the output plot: 

```
directory = '/location/mas_data/'
mas_output = MASOutput(directory)
br = mas_output['br']

# Do the tracing 
nseeds = 12
r = np.ones(nseeds**2)*30*u.R_sun
lat = np.linspace(-89, 89, nseeds**2, endpoint=False)*u.deg
lon = np.random.rand(nseeds**2)*360*u.deg
tracer = FortranTracer()
flines = tracer.trace(mas_output, r=r, lat=lat, lon=lon)

fig = plt.figure(figsize=(8,8))
ax = plt.subplot(111, projection='3d')

# draw the Sun 
solrad = 1
usph, vsph = np.mgrid[0:2*np.pi:20j, 0:np.pi:20j]
xsph = np.cos(usph)*np.sin(vsph)*solrad
ysph = np.sin(usph)*np.sin(vsph)*solrad
zsph = np.cos(vsph)*solrad
ax.plot_surface(xsph, ysph, zsph, color='orange', alpha=1)

# draw the field lines 
idx = 0
for fline in flines:
    color = (br.sample_at_coords(np.mod(fline.lon[idx], 2*np.pi*u.rad), fline.lat[idx], fline.r[idx]*u.R_sun) > 0)
    color = {1: 'crimson', 0: 'dodgerblue'}[int(color)]
    ax.plot3D(fline.xyz[:,0], fline.xyz[:,1], fline.xyz[:,2], color=color)

ax.set_title('MAS-MHD Coronal Solution')
for axis in 'xyz':
    getattr(ax, 'set_{}label'.format(axis))(axis+' (R$_\odot)$')
plt.show()
``` 

```
print(br.r_coords.min(), br.r_coords.max())
0.9995602369308472 solRad 30.511646270751953 solRad 
``` 
![image](https://user-images.githubusercontent.com/43330567/197417618-c645967d-0a7a-470d-a289-07164a183adf.png)

**Comment by AthKouloumvakos** [comment]
I do not think that the tracing has a problem.

What happens is that the tracer = FortranTracer() gets the default values for the maximum steps and the step size and this is a problem here because the tracing stops early before it reaches the boundary. Try the same example by increasing the maximum steps and probably reducing the step size.

**Comment by dstansby** [comment]
How many points does one of the field lines have? Just working on something else and I may have found an issue in specifying the tracing step size.

**Comment by AthKouloumvakos** [comment]
Without specifing the maximum step or the step size, so, `tracer = FortranTracer()`
the `print(fline.xyz.shape)` is `(2031, 3)`

For grater steps, `tracer = FortranTracer(max_steps=30000, step_size=1)`
the `print(fline.xyz.shape)` is `(59999, 3)` for the first FL for example.

**Comment by AthKouloumvakos** [comment]
I did some quick tests yesterday with the tracer which looks to work as it supposes to be
for example using: `tracer = FortranTracer(max_steps=30000, step_size=1)` 

I get a decent FLT as the plot below:
![image](https://user-images.githubusercontent.com/10522585/198312573-96b624ee-47f7-4013-ad11-17b77ed88210.png)

However, filtering a bit the FLs and zooming into a region I get the following view that shows that some improvement in the tracing part might be needed.

<img width="473" alt="Screen Shot 2022-10-27 at 10 21 26 AM" src="https://user-images.githubusercontent.com/10522585/198311975-8aea3643-fc1a-474f-bee2-6e40cff54376.png">

So some FLs are not traced properly. There are some kinks here and there that mess up the trace. This probably means that during the tracing the tracer may jump a little to some neighbour FLs when there is a stiff point on the tracer. There is a way to improve this. For example, a first thing is to increase the accuracy of the interpolator by using a cubic interpolation.

**Comment by dstansby** [comment]
Thanks for the detailed investigations! Some comments:

- Setting max_steps=30000 will allocate a (30000, 3) shaped array for every field line, evey if there are not 30,000 points traced, so be careful not to set very high maximum steps and eat up too much RAM
- The tracer uses a RK4 method with linear interpolation to do the tracing, but I'm far from an expert in whether that is good or bad or good enough for a given problem... The code for `streamtracer` is here: https://github.com/dstansby/streamtracer/tree/867453ece0d2d632f15c6f8a18ea464fc1c030a2 (I need to sort out the branches, as I did a re-write from FORTRAN > Rust that I haven't released yet because it's quite slow), but suggestions for improvement welcome. Alternatively if someone has another tracing backend that is better then I'd be up for adding the option to use that in `PsiPy`.

Given the original bug seems fixed I'll close this, but comment if I'm wrong there 😄

**Comment by thepeteriley** [comment]
> I did some quick tests yesterday with the tracer which looks to work as it supposes to be for example using: `tracer = FortranTracer(max_steps=30000, step_size=1)`
> 
> I get a decent FLT as the plot below: ![image](https://user-images.githubusercontent.com/10522585/198312573-96b624ee-47f7-4013-ad11-17b77ed88210.png)
> 
> However, filtering a bit the FLs and zooming into a region I get the following view that shows that some improvement in the tracing part might be needed.
> 
> <img alt="Screen Shot 2022-10-27 at 10 21 26 AM" width="473" src="https://user-images.githubusercontent.com/10522585/198311975-8aea3643-fc1a-474f-bee2-6e40cff54376.png">
> 
> So some FLs are not traced properly. There are some kinks here and there that mess up the trace. This probably means that during the tracing the tracer may jump a little to some neighbour FLs when there is a stiff point on the tracer. There is a way to improve this. For example, a first thing is to increase the accuracy of the interpolator by using a cubic interpolation.

You've just simulated switchbacks in a global, steady-state MHD calculation! That's amazing!!!

**Comment by MohamedNedal** [comment]
Thank you @dstansby  and @AthKouloumvakos  for your explanation. Here are some examples I tried:  

![image](https://user-images.githubusercontent.com/43330567/199794875-d6d5c9d8-b4b0-4112-b60b-c3ebe006d668.png)
![image](https://user-images.githubusercontent.com/43330567/199794958-0f3da452-a7bd-457e-8dad-07225fc76152.png)
![image](https://user-images.githubusercontent.com/43330567/199795110-85e5ff09-6920-428f-bf6d-0c6b0a39359c.png)

**Comment by MohamedNedal** [comment]
@AthKouloumvakos  Just out of curiosity, I was wondering how did you make this plot? :) 
![image](https://user-images.githubusercontent.com/43330567/199795798-6954545f-0e35-4033-975d-15c3e8e97059.png)

**Comment by dstansby** [comment]
What step sizes are you using for the above plots?

**Comment by MohamedNedal** [comment]
`step_size=1 `
I found that I can make `max_sizes` smaller by increasing the `step_size`

**Comment by AthKouloumvakos** [comment]
Hi @MohamedNedal, sorry for the late response. I have used [plotly](https://plotly.com) to make the above plot.

**Comment by MohamedNedal** [comment]
> Hi @MohamedNedal, sorry for the late response. I have used [plotly](https://plotly.com) to make the above plot.

Thank you very much
